#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Katsumi Sunahara
# SPDX-License-Identifier: BSD-3-Clause

import sys


def factor(n):
    # 階乗を計算する関数
    if n < 0:
        return "負の数には階乗の定義がありません。"
    elif n == 0 or n == 1:
        return 1
    else:
        res = 1
        for i in range(2, n + 1):
            res *= i
        return res



def main():
    # 標準入力から数値を受け取り、階乗を計算
    try:
        # 標準入力を受け取る
        inp_data = sys.stdin.read().strip()

        # 数値に変換できなければエラー
        num = int(inp_data)

        #階乗を計算して出力
        if num < 0:
            print("負の数には階乗の定義がありません。")
        else:
            print(f"{num} の階乗は{factor(num)}")
    except ValueError:
        print("整数を入力してください。")
        sys.exit(1)


main()
